// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvyjusjyhyksyzxxqxik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eWp1c2p5aHlrc3l6eHhxeGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODc0MTgsImV4cCI6MjA3MTk2MzQxOH0.8iNIY2eaWGiQ2bIPJa4ebR7X4XsY34P1BN9k0eMzGGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});